when:
  - event: push
    branch: ci_trial

steps:
  - name: build
    image: debian
    commands:
      - echo "Start Pipeline"
      - pip install sphinx sphinx-rtd-theme
      - ls
	  - sphinx-build . _build/
