when:
  - event: push
    branch: ci_trial

steps:
  - name: build
    image: debian
    commands:
      - echo "Start Pipeline"
      - python -m venv venv
      - /bin/bash -c "source venv/bin/activate"
      - python -m pip install --upgrade pip
      - python -m pip install sphinx sphinx-rtd-theme
      - ls
      - sphinx-build . _build/
