when:
  - event: push
    branch: ci_trial

steps:
  - name: build
    image: python:3.9-buster
    commands:
      - echo "Start Pipeline"
      - python3 -m venv venv
      - /bin/bash -c "source venv/bin/activate"
      - python3 -m pip install --upgrade pip
      - python3 -m pip install sphinx sphinx-rtd-theme myst-parser
      - ls
      - sphinx-build . _build/
