name: "Generate docs"

on:
  push:
    branches: [ ci_trial]
  pull_request:
    branches: [ main ]
  # Run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - uses: actions/checkout@v4
    - name: Install sphinx, build documentation
      run: |
        echo "Start Pipeline"        
        pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme myst-parser
        python3 generate_index.py
        ls
        sphinx-build . _build/
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: _build/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/ci_trial'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/
    - name: push to codeberg pages branch
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE/public
        git config --global init.defaultBranch pages
      # clone the existing pages branch which will be updated with new doc build
        git clone -b pages https://$CBTOKEN@codeberg.org/derreparierer/derreparierer.git build_docs
      # purge existing docs
        rm -rf build_docs/*
      # add new docs
        cp -a _build/* build_docs/
      # commit and push to pages branch
        cd build_docs/
        git remote set-url origin https://$CBTOKEN@codeberg.org/derreparierer/derreparierer.git
        git add --all
      # exclude current push from CI pipeline triggering
        git commit -m "deploy $GITHUB_SHA [ci skip]"
        git push -u origin pages
